export function ensureDir(pyodide, path) {
  if (!path || path === '/') return;
  const parts = path.split('/').filter(Boolean);
  let cur = '';
  for (const part of parts) {
    cur += '/' + part;
    try {
      pyodide.FS.mkdir(cur);
    } catch (err) {
      if (!String(err).includes('File exists')) throw err;
    }
  }
}

export function writeText(pyodide, path, text) {
  const dir = path.includes('/') ? path.slice(0, path.lastIndexOf('/')) : '';
  ensureDir(pyodide, dir);
  pyodide.FS.writeFile(path, text, { encoding: 'utf8' });
}

export function writeBinary(pyodide, path, bytes) {
  const dir = path.includes('/') ? path.slice(0, path.lastIndexOf('/')) : '';
  ensureDir(pyodide, dir);
  pyodide.FS.writeFile(path, bytes, { encoding: 'binary' });
}

export function snapshotDir(pyodide, root = '.') {
  const out = [];
  const walk = (p) => {
    let entries;
    try {
      entries = pyodide.FS.readdir(p);
    } catch {
      return;
    }
    for (const entry of entries) {
      if (entry === '.' || entry === '..') continue;
      const full = p === '/' ? `/${entry}` : `${p}/${entry}`;
      let stat;
      try {
        stat = pyodide.FS.stat(full);
      } catch {
        continue;
      }
      const mode = stat.mode;
      if (pyodide.FS.isDir(mode)) {
        walk(full);
      } else {
        out.push({ path: full, mtime: stat.mtime, size: stat.size });
      }
    }
  };
  walk(root);
  return out;
}

export const REQUIRED_FILES = [
  "art.py",
  "art_class.py",
  "art_render.py",
  "art_scheme.py",
  "art_bmp.py",
  "art_constants.txt",
  "art_settings.txt",
  "data/artists/core/afghanistan.json",
  "data/artists/core/alabama.json",
  "data/artists/core/alaska.json",
  "data/artists/core/angola.json",
  "data/artists/core/arizona.json",
  "data/artists/core/armenia.json",
  "data/artists/core/australia.json",
  "data/artists/core/barbados.json",
  "data/artists/core/belize.json",
  "data/artists/core/benin.json",
  "data/artists/core/bolivia.json",
  "data/artists/core/brazil.json",
  "data/artists/core/burkinafaso.json",
  "data/artists/core/capeverde.json",
  "data/artists/core/chad.json",
  "data/artists/core/colorado.json",
  "data/artists/core/comoros.json",
  "data/artists/core/congo.json",
  "data/artists/core/connecticut.json",
  "data/artists/core/djibouti.json",
  "data/artists/core/dominica.json",
  "data/artists/core/dominicanrepublic.json",
  "data/artists/core/ecuador.json",
  "data/artists/core/egypt.json",
  "data/artists/core/eritrea.json",
  "data/artists/core/eswatini.json",
  "data/artists/core/ethiopia.json",
  "data/artists/core/fiji.json",
  "data/artists/core/florida.json",
  "data/artists/core/gabon.json",
  "data/artists/core/gambia.json",
  "data/artists/core/ghana.json",
  "data/artists/core/grenada.json",
  "data/artists/core/guatemala.json",
  "data/artists/core/guinea.json",
  "data/artists/core/guineabissau.json",
  "data/artists/core/illinois.json",
  "data/artists/core/ivorycoast.json",
  "data/artists/core/kansas.json",
  "data/artists/core/kiribati.json",
  "data/artists/core/lesotho.json",
  "data/artists/core/liberia.json",
  "data/artists/core/libya.json",
  "data/artists/core/lol.gitkeep",
  "data/artists/core/madagascar.json",
  "data/artists/core/malawi.json",
  "data/artists/core/mali.json",
  "data/artists/core/marshall.json",
  "data/artists/core/mauritania.json",
  "data/artists/core/mauritius.json",
  "data/artists/core/micronesia.json",
  "data/artists/core/morocco.json",
  "data/artists/core/mozambique.json",
  "data/artists/core/namibia.json",
  "data/artists/core/nauru.json",
  "data/artists/core/newhampshire.json",
  "data/artists/core/newjersey.json",
  "data/artists/core/newzealand.json",
  "data/artists/core/niger.json",
  "data/artists/core/nigeria.json",
  "data/artists/core/northcarolina.json",
  "data/artists/core/palau.json",
  "data/artists/core/panama.json",
  "data/artists/core/papua.json",
  "data/artists/core/paraguay.json",
  "data/artists/core/pennsylvania.json",
  "data/artists/core/rwanda.json",
  "data/artists/core/saintkitts.json",
  "data/artists/core/samoa.json",
  "data/artists/core/saotome.json",
  "data/artists/core/senegal.json",
  "data/artists/core/seychelles.json",
  "data/artists/core/sierraleone.json",
  "data/artists/core/solomon.json",
  "data/artists/core/somalia.json",
  "data/artists/core/southafrica.json",
  "data/artists/core/southsudan.json",
  "data/artists/core/sudan.json",
  "data/artists/core/suriname.json",
  "data/artists/core/tanzania.json",
  "data/artists/core/tennessee.json",
  "data/artists/core/togo.json",
  "data/artists/core/tonga.json",
  "data/artists/core/trinidad.json",
  "data/artists/core/tunisia.json",
  "data/artists/core/tuvalu.json",
  "data/artists/core/uganda.json",
  "data/artists/core/uruguay.json",
  "data/artists/core/vanuatu.json",
  "data/artists/core/venezuela.json",
  "data/artists/core/vermont.json",
  "data/artists/core/westernsahara.json",
  "data/artists/core/westvirginia.json",
  "data/artists/core/wyoming.json",
  "data/artists/core/zambia.json",
  "data/artists/core/zimbabwe.json",
  "data/versions/core/afghanistan_alpha.json",
  "data/versions/core/alabama_alpha.json",
  "data/versions/core/alabama_beta.json",
  "data/versions/core/alaska_beta.json",
  "data/versions/core/angola_zeta.json",
  "data/versions/core/arizona_epsilon.json",
  "data/versions/core/armenia_alpha.json",
  "data/versions/core/armenia_beta.json",
  "data/versions/core/australia_alpha.json",
  "data/versions/core/barbados_delta.json",
  "data/versions/core/barbados_epsilon.json",
  "data/versions/core/barbados_gamma.json",
  "data/versions/core/belize_beta.json",
  "data/versions/core/belize_delta.json",
  "data/versions/core/belize_epsilon.json",
  "data/versions/core/belize_gamma.json",
  "data/versions/core/belize_gamma2.json",
  "data/versions/core/benin_beta.json",
  "data/versions/core/benin_gamma.json",
  "data/versions/core/bolivia_alpha.json",
  "data/versions/core/brazil_delta.json",
  "data/versions/core/brazil_gamma.json",
  "data/versions/core/burkinafaso_alpha.json",
  "data/versions/core/capeverde_alpha.json",
  "data/versions/core/capeverde_beta.json",
  "data/versions/core/chad_alpha.json",
  "data/versions/core/chad_beta.json",
  "data/versions/core/chad_delta.json",
  "data/versions/core/chad_epsilon.json",
  "data/versions/core/chad_gamma.json",
  "data/versions/core/colorado_beta.json",
  "data/versions/core/colorado_gamma.json",
  "data/versions/core/comoros_alpha.json",
  "data/versions/core/congo_alpha.json",
  "data/versions/core/connecticut_gamma.json",
  "data/versions/core/djibouti_alpha.json",
  "data/versions/core/djibouti_beta.json",
  "data/versions/core/dominica_alpha.json",
  "data/versions/core/dominica_gamma.json",
  "data/versions/core/dominicanrepublic_alpha.json",
  "data/versions/core/ecuador_beta.json",
  "data/versions/core/egypt_alpha.json",
  "data/versions/core/egypt_beta.json",
  "data/versions/core/eritrea_alpha.json",
  "data/versions/core/eswatini_alpha.json",
  "data/versions/core/ethiopia_alpha.json",
  "data/versions/core/fiji_alpha.json",
  "data/versions/core/florida_beta.json",
  "data/versions/core/florida_gamma.json",
  "data/versions/core/gabon_alpha.json",
  "data/versions/core/gambia_alpha.json",
  "data/versions/core/ghana_alpha.json",
  "data/versions/core/ghana_beta.json",
  "data/versions/core/grenada_alpha.json",
  "data/versions/core/grenada_beta.json",
  "data/versions/core/guatemala_alpha.json",
  "data/versions/core/guatemala_beta.json",
  "data/versions/core/guinea_alpha.json",
  "data/versions/core/guinea_beta.json",
  "data/versions/core/guineabissau_alpha.json",
  "data/versions/core/illinois_delta.json",
  "data/versions/core/illinois_epsilon.json",
  "data/versions/core/illinois_gamma.json",
  "data/versions/core/ivorycoast_alpha.json",
  "data/versions/core/kansas_delta.json",
  "data/versions/core/kansas_epsilon.json",
  "data/versions/core/kansas_gamma.json",
  "data/versions/core/kiribati_alpha.json",
  "data/versions/core/kiribati_beta.json",
  "data/versions/core/lesotho_alpha.json",
  "data/versions/core/liberia_alpha.json",
  "data/versions/core/liberia_beta.json",
  "data/versions/core/libya_alpha.json",
  "data/versions/core/lol.gitkeep",
  "data/versions/core/madagascar_alpha.json",
  "data/versions/core/madagascar_beta.json",
  "data/versions/core/malawi_alpha.json",
  "data/versions/core/malawi_beta.json",
  "data/versions/core/mali_alpha.json",
  "data/versions/core/mali_beta.json",
  "data/versions/core/marshall_17v1110300390.json",
  "data/versions/core/marshall_alpha.json",
  "data/versions/core/mauritania_alpha.json",
  "data/versions/core/mauritania_beta.json",
  "data/versions/core/mauritius_alpha.json",
  "data/versions/core/micronesia_alpha.json",
  "data/versions/core/morocco_alpha.json",
  "data/versions/core/mozambique_alpha.json",
  "data/versions/core/namibia_alpha.json",
  "data/versions/core/namibia_beta.json",
  "data/versions/core/namibia_delta.json",
  "data/versions/core/namibia_gamma.json",
  "data/versions/core/nauru_alpha.json",
  "data/versions/core/newhampshire_alpha.json",
  "data/versions/core/newhampshire_beta.json",
  "data/versions/core/newhampshire_delta.json",
  "data/versions/core/newjersey_delta.json",
  "data/versions/core/newjersey_gamma.json",
  "data/versions/core/newzealand_alpha.json",
  "data/versions/core/niger_alpha.json",
  "data/versions/core/niger_beta.json",
  "data/versions/core/niger_gamma.json",
  "data/versions/core/nigeria_alpha.json",
  "data/versions/core/northcarolina_beta.json",
  "data/versions/core/palau_alpha.json",
  "data/versions/core/panama_eta.json",
  "data/versions/core/papua_alpha.json",
  "data/versions/core/paraguay_beta.json",
  "data/versions/core/paraguay_delta.json",
  "data/versions/core/paraguay_gamma.json",
  "data/versions/core/pennsylvania_epsilon.json",
  "data/versions/core/pennsylvania_zeta.json",
  "data/versions/core/rwanda_alpha.json",
  "data/versions/core/saintkitts_alpha.json",
  "data/versions/core/saintkitts_beta.json",
  "data/versions/core/saintkitts_delta.json",
  "data/versions/core/samoa_alpha.json",
  "data/versions/core/saotome_alpha.json",
  "data/versions/core/saotome_beta.json",
  "data/versions/core/senegal_alpha.json",
  "data/versions/core/seychelles_alpha.json",
  "data/versions/core/sierraleone_alpha.json",
  "data/versions/core/solomon_1v2495200390.json",
  "data/versions/core/solomon_alpha.json",
  "data/versions/core/somalia_alpha.json",
  "data/versions/core/southafrica_alpha.json",
  "data/versions/core/southsudan_65v1110300390.json",
  "data/versions/core/southsudan_alpha.json",
  "data/versions/core/southsudan_beta.json",
  "data/versions/core/sudan_alpha.json",
  "data/versions/core/suriname_epsilon.json",
  "data/versions/core/tanzania_alpha.json",
  "data/versions/core/tanzania_beta.json",
  "data/versions/core/tanzania_gamma.json",
  "data/versions/core/tennessee_beta.json",
  "data/versions/core/tennessee_gamma.json",
  "data/versions/core/togo_alpha.json",
  "data/versions/core/tonga_alpha.json",
  "data/versions/core/trinidad_gamma.json",
  "data/versions/core/tunisia_alpha.json",
  "data/versions/core/tuvalu_alpha.json",
  "data/versions/core/uganda_alpha.json",
  "data/versions/core/uruguay_beta.json",
  "data/versions/core/vanuatu_alpha.json",
  "data/versions/core/venezuela_alpha.json",
  "data/versions/core/venezuela_gamma.json",
  "data/versions/core/vermont_delta.json",
  "data/versions/core/westernsahara_alpha.json",
  "data/versions/core/westvirginia_delta.json",
  "data/versions/core/westvirginia_gamma.json",
  "data/versions/core/wyoming_epsilon.json",
  "data/versions/core/wyoming_gamma.json",
  "data/versions/core/zambia_alpha.json",
  "data/versions/core/zimbabwe_alpha.json"
];
